version: 1.0.{build}
image: Visual Studio 2015
skip_tags: true
skip_branch_with_pr: true
clone_depth: 1
install:
- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86'
- cmd: git clone -b v2.1 --single-branch --depth=1 https://github.com/fiendish/LuaJIT.git C:\luajit
- ps: pushd c:\luajit\src
- ps: (Get-Content msvcbuild.bat) | ForEach-Object { $_ -replace " /MD " , " /MT " } | Set-Content msvcbuild.bat
- ps: (Get-Content msvcbuild.bat) -replace "^@set LJCOMPILE=cl /nologo /c /O2 /W3 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_STDIO_INLINE=__declspec\(dllexport\)__inline", "@set LJCOMPILE=cl /nologo /c /O2 /W3 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_STDIO_INLINE=__declspec(dllexport)__inline /DLUAJIT_ENABLE_LUA52COMPAT" | Set-Content msvcbuild.bat
- cmd: ./msvcbuild.bat
- cmd: copy luajit.exe C:\
- cmd: copy lua51.* C:\
- ps: |
      Get-ChildItem .\luajit.exe -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      Get-ChildItem .\lua51.* -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
build: off
before_deploy:
- ps: |
    git config --global credential.helper store
    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n"
    git config --global user.name "fiendish"
    git config --global user.email "patcherton.fixesthings@gmail.com"
deploy:
- provider: GitHub
  tag: latest
  auth_token:
    secure: sc2iImdfbB8Q0GWI90ElJqiWh9kCN/siFoVoJx1+XgAyG67GE2pzGQ+uzPQHU1Bt
  artifact: /.*/
  force_update: true
after_deploy:
- cmd:
